version: "3.5"

services:
    consul-server:
        image: consul-bld:local
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:8600"
            - "8600:8600/udp"
        networks:
            - bld
            
    main-dns:
        image: main-dns:local
        ports:
            - "8080:8080"
        dns:    
            - 127.0.0.1
        networks:
            - bld
            
    sub-dns:
        image: sub-dns:local
        dns:
            - 127.0.0.1
        networks:
            - bld
            
networks:
    bld: